version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11 # Använd den Java-version din applikation behöver
  
  build:
    commands:
      - echo "Building the project..."
      - mvn clean install # Bygger projektet

artifacts:
  files:
    - target/webservice-app.jar # Det färdiga JAR-artefakten att distribuera
