version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto-17  # Använd Java 17
  pre_build:
    commands:
      - echo "Nothing to do in the pre_build phase..."  # Meddelande för pre_build-fasen
  build:
    commands:
      - echo "Build started on `date`"
      - cd molndalAPIExample  # Navigera till rätt katalog
      - mvn install -DskipTests  # Installera beroenden utan att köra tester
      - mvn clean package  # Bygg paketet

  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - molndalAPIExample/target/webservice-app.jar  # Sökväg till artifact
  discard-paths: yes  # Ta bort sökvägar från artifacts
