version: 0.2

env:
  variables:
    DB_NAME: "webservice"
    DB_SERVER: "webservice-db.chcwmoqw0h8e.eu-north-1.rds.amazonaws.com"
    DB_URL: "jdbc:mysql://webservice-db.chcwmoqw0h8e.eu-north-1.rds.amazonaws.com:3306/webservice?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    USER_NAME: "root"
    PASSWORD: "Guppie88!"
    PORT: "5000"

phases:
  install:
    runtime-versions:
      java: corretto21

  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...

  build:
    commands:
      - echo Build started on `date`
      - mvn clean install  # Kör mvn install från projektets rot
      - mvn clean package  # Paketera applikationen

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading artifacts to S3...
      - aws s3 cp target/webservice-app.jar s3://elasticbeanstalk-eu-north-1-147997133062/ --recursive
      - echo Creating a new application version in Elastic Beanstalk...
      - aws elasticbeanstalk create-application-version --application-name BookserviceAS --version-label `date +%Y%m%d%H%M%S` --source-bundle S3Bucket="elasticbeanstalk-eu-north-1-147997133062",S3Key="target/webservice-app.jar"
      - echo Updating Elastic Beanstalk environment...
      - aws elasticbeanstalk update-environment --environment-name BookserviceAS --version-label `date +%Y%m%d%H%M%S`

artifacts:
  files:
    - target/webservice-app.jar
  discard-paths: yes
