version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21  # Använd Corretto 21 för att matcha med workflow-inställningen
  pre_build:
    commands:
      - echo Preparing the build environment...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install  # Bygg hela multimodulprojektet
      - echo Build and packaging completed
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading artifacts to S3...
      - aws s3 cp BookserviceAS/target/*.jar s3://elasticbeanstalk-eu-north-1-147997133062/ --recursive
      - aws s3 cp molndalAPIExample/target/*.jar s3://elasticbeanstalk-eu-north-1-147997133062/ --recursive
      - echo Creating a new application version in Elastic Beanstalk...
      - aws elasticbeanstalk create-application-version --application-name BookserviceAS --version-label `date +%Y%m%d%H%M%S` --source-bundle S3Bucket="elasticbeanstalk-eu-north-1-147997133062",S3Key="BookserviceAS/target/*.jar"
      - aws elasticbeanstalk create-application-version --application-name BookserviceAS --version-label `date +%Y%m%d%H%M%S` --source-bundle S3Bucket="elasticbeanstalk-eu-north-1-147997133062",S3Key="molndalAPIExample/target/*.jar"
      - echo Updating Elastic Beanstalk environment...
      - aws elasticbeanstalk update-environment --environment-name BookserviceAS --version-label `date +%Y%m%d%H%M%S`

artifacts:
  files:
    - BookserviceAS/target/*.jar  # Om BookserviceAS producerar en .jar-fil
    - molndalAPIExample/target/*.jar  # Om molndalAPIExample producerar en .jar-fil
  discard-paths: yes
