version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
