version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21  # Använd Corretto 21

  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...

  build:
    commands:
      - echo Build started on `date`
      - cd molndalAPIExample  # Navigera till rätt katalog
      - mvn install
      - mvn clean package

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - molndalAPIExample/target/webservice-app.jar
  discard-paths: yes
