version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21  # Använd Corretto 21 för att matcha med workflow-inställningen
  pre_build:
    commands:
      - echo Preparing the build environment...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install  # Bygg hela multimodulprojektet
      - echo Build and packaging completed
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - BookserviceAS/target/*.jar  # Om BookserviceAS producerar en .jar-fil
    - molndalAPIExample/target/*.jar  # Om molndalAPIExample producerar en .jar-fil
  discard-paths: yes
