version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto-17  # Se till att använda Java 17
    commands:
      - echo "Installing custom Corretto(OpenJDK) version 17 ..."
      - apt-get update
      - apt-get install -y java-17-amazon-corretto-jdk  # Rätt stavning på paketnamnet
      - cd molndalAPIExample  # Navigera till rätt katalog
      - mvn install -DskipTests

  build:
    commands:
      - echo "Build started on `date`"
      - mvn clean package

  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - molndalAPIExample/target/*.jar  # Uppdatera sökvägen till artifacts om det behövs
