version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - mvn install -DskipTests

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/*.jar
