name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/BookserviceAS/molndalAPIExample/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies and run tests
        working-directory: BookserviceAS/molndalAPIExample  # Sätt arbetskatalog till BookserviceAS/molndalAPIExample
        run: mvn clean install  # Kör bygg och tester

      - name: Verify Tests Results
        if: failure()
        run: cat BookserviceAS/molndalAPIExample/target/surefire-reports/*.txt  # Visar testresultat om något går fel
