name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4  # Uppdaterad till senaste versionen

      - name: Set up JDK 21
        uses: actions/setup-java@v4  # Använder Temurin JDK version 21
        with:
          java-version: '21'
          distribution: 'temurin'  # Använder Temurin JDK

      - name: Cache Maven packages
        uses: actions/cache@v4  # Uppdaterad till senaste versionen
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies and run tests for molndalAPIExample
        working-directory: molndalAPIExample  # Byter till molndalAPIExample-katalogen
        run: mvn clean install  # Kör mvn clean install för molndalAPIExample

      - name: Install dependencies and run tests for webservice
        working-directory: webservice  # Byter till webservice-katalogen
        run: mvn clean install  # Kör mvn clean install för webservice
