name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4  # Senaste versionen av GitHub Actions Checkout

      - name: Set up JDK 21
        uses: actions/setup-java@v4  # Senaste versionen av Java Setup Action
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4  # Senaste versionen av Cache Action
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies and run tests
        working-directory: molndalAPIExample  # Detta säkerställer att Maven körs i rätt katalog
        run: mvn clean install  # Kör mvn clean install för att bygga och testa
