name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4  # Uppdaterad till senaste versionen som stödjer Node.js 20

      - name: Set up JDK 22
        uses: actions/setup-java@v4  # Uppdaterad till senaste versionen som stödjer Node.js 20
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4  # Uppdaterad till senaste versionen som stödjer Node.js 20
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies and run tests
        working-directory: molndalAPIExample  # Sätt arbetskatalog till molndalAPIExample
        run: mvn clean install -P test  # Kör Maven med "test"-profil om det behövs
