name: Build and Deploy to AWS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Corretto 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
      
      - name: Build with Maven
        run: mvn clean package
      
      - name: Kontrollera att JAR-filen skapades i target-katalogen
        run: ls -l target
      
      - name: Archive built JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: target/*.jar
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download JAR from build
        uses: actions/download-artifact@v4
        with:
          name: jar-file
      
      - name: Kontrollera arbetskatalog
        run: pwd
      
      - name: Lista filer i arbetskatalogen
        run: ls -l
      
      - name: Skapa target-katalog (om den saknas)
        run: mkdir -p target
      
      - name: Flytta nedladdad JAR till target-katalogen
        run: mv *.jar target/
      
      - name: Lista filer efter att JAR-filen har flyttats
        run: ls -l target
      
      - name: Rename JAR with timestamp
        run: mv target/webservice-0.0.1-SNAPSHOT.jar target/webservice-${{ github.run_id }}.jar
        continue-on-error: true
      
      - name: List files after rename
        run: ls -l target
      
      - name: Upload JAR to S3
        run: aws s3 cp target/webservice-${{ github.run_id }}.jar s3://elasticbeanstalk-eu-north-1-147997133062/artifact/
        continue-on-error: true
      
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name Bookservice --version-label ${{ github.run_id }} --source-bundle S3Bucket="elasticbeanstalk-eu-north-1-147997133062",S3Key="artifact/webservice-${{ github.run_id }}.jar"
          aws elasticbeanstalk update-environment --application-name Bookservice --environment-name Bookservice-env --version-label ${{ github.run_id }}
        continue-on-error: true
      
      - name: Kontrollera AWS CLI version
        run: aws --version
      
      - name: Verifiera S3-bucket location
        run: aws s3api get-bucket-location --bucket elasticbeanstalk-eu-north-1-147997133062
