name: Build and Deploy BookserviceAS to Elastic Beanstalk

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_LOCATION: ./pom.xml  # Eftersom pom.xml ligger i root

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Corretto 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
      
      - name: List files for verification  # Lägger till detta för att säkerställa filstrukturen
        run: ls -R
      
      - name: Build with Maven
        run: mvn -f ${{ env.PROJECT_LOCATION }} clean package  # Använder ./pom.xml eftersom den finns i root
      
      - name: Package application
        run: |
          mkdir -p deploy
          cp target/*.jar deploy/
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-files
          path: deploy/
  
  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  # Rätt region
      
      - name: Deploy to Elastic Beanstalk
        run: |
          aws s3 cp deploy/*.jar s3://elasticbeanstalk-eu-north-1-${{ secrets.AWS_ACCOUNT_ID }}/artifact/
          aws elasticbeanstalk create-application-version --application-name ${{ env.ELASTIC_BEANSTALK_APP_NAME }} --version-label ${{ github.run_id }} --source-bundle S3Bucket="elasticbeanstalk-eu-north-1-${{ secrets.AWS_ACCOUNT_ID }}",S3Key="artifact/*.jar"
          aws elasticbeanstalk update-environment --application-name ${{ env.ELASTIC_BEANSTALK_APP_NAME }} --environment-name ${{ env.ELASTIC_BEANSTALK_ENV_NAME }} --version-label ${{ github.run_id }}
