name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4  # Uppdaterad till senaste versionen

      - name: Set up JDK 21
        uses: actions/setup-java@v4  # Uppdaterad till senaste versionen
        with:
          java-version: '21"
          distribution: 'temurin'  # Använder Temurin JDK
          distribution: ''

      - name: Cache Maven packages
        uses: actions/cache@v4  # Uppdaterad till senaste versionen
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies and run tests
        working-directory: molndalAPIExample  # Uppdaterad katalog till molndalAPIExample eller molndal books
        run: mvn clean install  # Kör mvn clean install för att installera beroenden och köra tester
