name: Build and Deploy BookserviceAS to AWS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_LOCATION: ./pom.xml
  ELASTIC_BEANSTALK_APP_NAME: "Bookservice"
  ELASTIC_BEANSTALK_ENV_NAME: "e-hahppfasmc"
  AWS_BUCKET_NAME: "elasticbeanstalk-eu-north-1-147997133062"
  JAR_FILE_NAME: "webservice-0.0.1-SNAPSHOT.jar"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Corretto 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
      
      - name: Build with Maven
        run: mvn clean package -f ${{ env.PROJECT_LOCATION }}
      
      - name: Run tests
        run: mvn test
      
      - name: List files in target directory
        run: ls -R target
      
      - name: Archive built JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: target/${{ env.JAR_FILE_NAME }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-file
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      
      - name: List target directory for verification
        run: ls target  # Verifiera att filen finns
      
      - name: Upload JAR to S3
        run: |
          aws s3 cp target/${{ env.JAR_FILE_NAME }} s3://${{ env.AWS_BUCKET_NAME }}/artifact/
      
      - name: Create new Elastic Beanstalk application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ env.ELASTIC_BEANSTALK_APP_NAME }} \
            --version-label ${{ github.run_id }} \
            --source-bundle S3Bucket="${{ env.AWS_BUCKET_NAME }}",S3Key="artifact/${{ env.JAR_FILE_NAME }}"
      
      - name: Deploy new version to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --application-name ${{ env.ELASTIC_BEANSTALK_APP_NAME }} \
            --environment-name ${{ env.ELASTIC_BEANSTALK_ENV_NAME }} \
            --version-label ${{ github.run_id }}
