name: Build and Deploy to AWS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Corretto 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
      
      - name: Build with Maven
        run: mvn clean package
      
      - name: List files in target directory
        run: ls -l target
      
      - name: Archive built JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: target/*.jar
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download JAR from build
        uses: actions/download-artifact@v4
        with:
          name: jar-file
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      
      - name: Kontrollera arbetskatalog
        run: pwd
      
      - name: Lista filer efter nedladdning
        run: ls -l
      
      - name: Rename JAR with timestamp
        run: mv webservice-0.0.1-SNAPSHOT.jar webservice-${{ github.run_id }}.jar
      
      - name: Kontrollera S3-konfiguration och version
        run: |
          aws --version
          aws configure list
          aws sts get-caller-identity
      
      - name: Upload JAR to S3
        run: aws s3 cp webservice-${{ github.run_id }}.jar s3
