name: Build and Deploy to AWS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Corretto 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
      
      - name: Build with Maven
        run: mvn clean package
      
      - name: List files in target directory
        run: ls -l target
      
      - name: Archive built JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: target/*.jar
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download JAR from build
        uses: actions/download-artifact@v4
        with:
          name: jar-file
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: $
          aws-region: ''
