name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4  # Kollar ut källkoden vid varje push/pull_request
      
      - name: Notify CodeBuild
        run: |
          aws codebuild start-build --project-name BookserviceAS-Build
