name: Build and Deploy to AWS

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Corretto 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
      
      - name: Build with Maven
        run: mvn clean package
      
      - name: List files in target directory
        run: ls -l target
      
      - name: Archive built JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: target/webservice-11315236611.jar  # Här används det nya filnamnet
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download JAR from build
        uses: actions/download-artifact@v4
        with:
          name: jar-file
      
      - name: Kontrollera arbetskatalog
        run: pwd
      
      - name: Lista filer efter nedladdning
        run: ls -l
      
      - name: Upload JAR to S3
        run: aws s3 cp webservice-11315236611.jar s3://elasticbeanstalk-eu-north-1-147997133062/artifact/
      
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name Bookservice --version-label ${{ github.run_id }} --source-bundle S3Bucket="elasticbeanstalk-eu-north-1-147997133062",S3Key="artifact/webservice-11315236611.jar"
          aws elasticbeanstalk update-environment --application-name Bookservice --environment-name Bookservice-env --version-label ${{ github.run_id }}
